<?php

namespace Database\Seeders;

use App\Models\MataKuliah;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MataKuliahSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $mataKuliah = [
            // Semester 1 (2023/1)
            [
                'kode' => 'KF57201111',
                'nama' => 'KALKULUS I',
                'deskripsi' => 'Mata kuliah yang membahas konsep dasar kalkulus diferensial dan integral satu variabel, limit, kontinuitas, turunan, dan aplikasinya dalam sistem informasi.',
                'sks' => 3,
                'semester' => 1,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],
            [
                'kode' => 'KF57201112',
                'nama' => 'BAHASA INGGRIS',
                'deskripsi' => 'Mata kuliah yang mengembangkan kemampuan bahasa Inggris dalam konteks akademik dan profesional, khususnya untuk bidang teknologi informasi.',
                'sks' => 2,
                'semester' => 1,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],
            [
                'kode' => 'KJ57201111',
                'nama' => 'FISIKA I',
                'deskripsi' => 'Mata kuliah yang membahas konsep dasar fisika meliputi mekanika, termodinamika, dan aplikasinya dalam teknologi informasi.',
                'sks' => 2,
                'semester' => 1,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],
            [
                'kode' => 'KJ57201112',
                'nama' => 'MANAJEMEN DAN ORGANISASI',
                'deskripsi' => 'Mata kuliah yang membahas konsep dasar manajemen, teori organisasi, dan penerapannya dalam lingkungan sistem informasi.',
                'sks' => 3,
                'semester' => 1,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],
            [
                'kode' => 'KJ57201113',
                'nama' => 'KONSEP SISTEM INFORMASI',
                'deskripsi' => 'Mata kuliah pengantar yang membahas konsep dasar sistem informasi, komponen sistem, dan peran sistem informasi dalam organisasi.',
                'sks' => 3,
                'semester' => 1,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],
            [
                'kode' => 'KJ57201114',
                'nama' => 'DASAR PEMROGRAMAN',
                'deskripsi' => 'Mata kuliah yang membahas konsep dasar pemrograman, algoritma, struktur kontrol, dan pengenalan bahasa pemrograman.',
                'sks' => 3,
                'semester' => 1,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],
            [
                'kode' => 'KU57201111',
                'nama' => 'PANCASILA',
                'deskripsi' => 'Mata kuliah yang membahas nilai-nilai Pancasila sebagai dasar negara dan implementasinya dalam kehidupan bermasyarakat.',
                'sks' => 2,
                'semester' => 1,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],
            [
                'kode' => 'KU57201112',
                'nama' => 'BAHASA INDONESIA',
                'deskripsi' => 'Mata kuliah yang mengembangkan kemampuan berbahasa Indonesia yang baik dan benar dalam komunikasi ilmiah dan profesional.',
                'sks' => 2,
                'semester' => 1,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],

            // Semester 2 (2023/2)
            [
                'kode' => 'KF57201121',
                'nama' => 'KALKULUS II',
                'deskripsi' => 'Lanjutan dari Kalkulus I yang membahas kalkulus multivariabel, integral rangkap, dan aplikasinya dalam sistem informasi.',
                'sks' => 3,
                'semester' => 2,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],
            [
                'kode' => 'KJ57201121',
                'nama' => 'FISIKA II',
                'deskripsi' => 'Lanjutan dari Fisika I yang membahas listrik, magnet, gelombang, dan aplikasinya dalam teknologi informasi.',
                'sks' => 3,
                'semester' => 2,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],
            [
                'kode' => 'KJ57201122',
                'nama' => 'SISTEM BASIS DATA',
                'deskripsi' => 'Mata kuliah yang membahas konsep dasar basis data, model data, normalisasi, dan perancangan sistem basis data.',
                'sks' => 3,
                'semester' => 2,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],
            [
                'kode' => 'KJ57201123',
                'nama' => 'LOGIKA DAN STRUKTUR DATA',
                'deskripsi' => 'Mata kuliah yang membahas logika matematika, struktur data, algoritma, dan implementasinya dalam pemrograman.',
                'sks' => 3,
                'semester' => 2,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],
            [
                'kode' => 'KU57201121',
                'nama' => 'KEWARGANEGARAAN',
                'deskripsi' => 'Mata kuliah yang membahas hak dan kewajiban warga negara, demokrasi, dan civic engagement dalam konteks modern.',
                'sks' => 2,
                'semester' => 2,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],
            [
                'kode' => 'KU57201122',
                'nama' => 'AGAMA',
                'deskripsi' => 'Mata kuliah yang membahas nilai-nilai agama dan implementasinya dalam kehidupan bermasyarakat dan berbangsa.',
                'sks' => 2,
                'semester' => 2,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],
            [
                'kode' => 'KU57201123',
                'nama' => 'LITERASI TEKNOLOGI INFORMASI',
                'deskripsi' => 'Mata kuliah yang membahas konsep dasar teknologi informasi, literasi digital, dan etika penggunaan teknologi.',
                'sks' => 2,
                'semester' => 2,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],
            [
                'kode' => 'KU57201124',
                'nama' => 'KEWIRAUSAHAAN',
                'deskripsi' => 'Mata kuliah yang membahas konsep dasar kewirausahaan, inovasi, dan pengembangan bisnis berbasis teknologi.',
                'sks' => 2,
                'semester' => 2,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],

            // Semester 3 (2024/1)
            [
                'kode' => 'KF57201231',
                'nama' => 'STATISTIKA DAN PROBABILITAS',
                'deskripsi' => 'Mata kuliah yang membahas konsep statistika deskriptif, inferensial, probabilitas, dan aplikasinya dalam analisis data sistem informasi.',
                'sks' => 2,
                'semester' => 3,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],
            [
                'kode' => 'KJ57201231',
                'nama' => 'PEMROGRAMAN WEB',
                'deskripsi' => 'Mata kuliah yang membahas teknologi pengembangan web, HTML, CSS, JavaScript, dan framework pengembangan web modern.',
                'sks' => 3,
                'semester' => 3,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],
            [
                'kode' => 'KJ57201232',
                'nama' => 'SISTEM INFORMASI MANAJEMEN',
                'deskripsi' => 'Mata kuliah yang membahas konsep sistem informasi dalam konteks manajemen, decision support system, dan executive information system.',
                'sks' => 2,
                'semester' => 3,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],
            [
                'kode' => 'KJ57201233',
                'nama' => 'REKAYASA KEBUTUHAN PERANGKAT LUNAK',
                'deskripsi' => 'Mata kuliah yang membahas proses analisis, dokumentasi, dan manajemen kebutuhan dalam pengembangan perangkat lunak.',
                'sks' => 3,
                'semester' => 3,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],
            [
                'kode' => 'KJ57201234',
                'nama' => 'MANAJEMEN PROSES BISNIS',
                'deskripsi' => 'Mata kuliah yang membahas analisis, perancangan, implementasi, dan optimasi proses bisnis dalam organisasi.',
                'sks' => 3,
                'semester' => 3,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],
            [
                'kode' => 'KJ57201235',
                'nama' => 'MANAJEMEN BASIS DATA',
                'deskripsi' => 'Mata kuliah yang membahas administrasi basis data, keamanan data, backup recovery, dan optimasi performa basis data.',
                'sks' => 3,
                'semester' => 3,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],
            [
                'kode' => 'KJ57201236',
                'nama' => 'SISTEM OPERASI',
                'deskripsi' => 'Mata kuliah yang membahas konsep sistem operasi, manajemen memori, proses, file system, dan keamanan sistem.',
                'sks' => 3,
                'semester' => 3,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],
            [
                'kode' => 'KJ57201357',
                'nama' => 'KOMUNIKASI BISNIS',
                'deskripsi' => 'Mata kuliah yang membahas teknik komunikasi efektif dalam lingkungan bisnis dan teknologi informasi.',
                'sks' => 2,
                'semester' => 3,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],
            [
                'kode' => 'KU57201231',
                'nama' => 'PENDIDIKAN ANTI KORUPSI',
                'deskripsi' => 'Mata kuliah yang membahas nilai-nilai integritas, transparansi, dan akuntabilitas dalam kehidupan bermasyarakat dan berprofesi.',
                'sks' => 1,
                'semester' => 3,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],

            // Semester 4 (2024/2)
            [
                'kode' => 'KF57201241',
                'nama' => 'ANALISIS NUMERIK',
                'deskripsi' => 'Mata kuliah yang membahas metode numerik untuk menyelesaikan masalah matematika dalam komputasi dan sistem informasi.',
                'sks' => 2,
                'semester' => 4,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],
            [
                'kode' => 'KJ57201241',
                'nama' => 'DESAIN DAN MANAJEMEN JARINGAN KOMPUTER',
                'deskripsi' => 'Mata kuliah yang membahas perancangan, implementasi, dan manajemen jaringan komputer untuk mendukung sistem informasi.',
                'sks' => 3,
                'semester' => 4,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],
            [
                'kode' => 'KJ57201242',
                'nama' => 'RANCANG BANGUN PERANGKAT LUNAK',
                'deskripsi' => 'Mata kuliah yang membahas metodologi pengembangan perangkat lunak, SDLC, dan implementasi sistem informasi.',
                'sks' => 3,
                'semester' => 4,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],
            [
                'kode' => 'KJ57201243',
                'nama' => 'MANAJEMEN PROYEK SISTEM INFORMASI',
                'deskripsi' => 'Mata kuliah yang membahas perencanaan, pelaksanaan, dan pengendalian proyek pengembangan sistem informasi.',
                'sks' => 3,
                'semester' => 4,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],
            [
                'kode' => 'KJ57201244',
                'nama' => 'SISTEM ENTERPRISE',
                'deskripsi' => 'Mata kuliah yang membahas sistem informasi tingkat enterprise, ERP, CRM, dan integrasi sistem dalam organisasi besar.',
                'sks' => 3,
                'semester' => 4,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],
            [
                'kode' => 'KJ57201245',
                'nama' => 'TRANSFORMASI DIGITAL',
                'deskripsi' => 'Mata kuliah yang membahas konsep transformasi digital, digitalisasi proses bisnis, dan teknologi emerging.',
                'sks' => 2,
                'semester' => 4,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],
            [
                'kode' => 'KJ57201246',
                'nama' => 'PEMROGRAMAN BERORIENTASI OBJEK',
                'deskripsi' => 'Mata kuliah yang membahas konsep pemrograman berorientasi objek, desain pattern, dan implementasinya dalam pengembangan sistem.',
                'sks' => 3,
                'semester' => 4,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],
            [
                'kode' => 'KJ57201363',
                'nama' => 'METODOLOGI PENELITIAN',
                'deskripsi' => 'Mata kuliah yang membahas metode penelitian ilmiah, desain penelitian, dan penulisan karya ilmiah dalam bidang sistem informasi.',
                'sks' => 2,
                'semester' => 4,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],
            [
                'kode' => 'KJ57201364',
                'nama' => 'KEAMANAN SISTEM INFORMASI',
                'deskripsi' => 'Mata kuliah yang membahas konsep keamanan informasi, kriptografi, manajemen risiko, dan implementasi keamanan sistem.',
                'sks' => 3,
                'semester' => 4,
                'program_studi' => 'Sistem Informasi',
                'fakultas' => 'Teknik',
                'is_active' => true,
            ],
        ];

        foreach ($mataKuliah as $mk) {
            MataKuliah::create($mk);
        }
    }
}